require './rb/templates/1.rb'
require './rb/templates/2.rb'
require './rb/templates/3.rb'
require './rb/templates/4.rb'
require './rb/templates/5.rb'
require './rb/templates/example_home.rb'
require './rb/templates/test_dungeon.rb'
require './rb/templates/test_plains.rb'